/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'status' : BookingStatus,
  'checkIn' : [] | [string],
  'listingId' : [] | [string],
  'createdAt' : bigint,
  'guestName' : string,
  'passengers' : [] | [bigint],
  'email' : string,
  'pickupDate' : [] | [string],
  'notes' : string,
  'bookingType' : BookingType,
  'checkOut' : [] | [string],
  'phone' : string,
  'totalPrice' : number,
  'taxiRouteId' : [] | [string],
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type BookingType = { 'listing' : null } |
  { 'taxi' : null };
export type ExternalBlob = Uint8Array;
export interface Listing {
  'id' : string,
  'pricePerNight' : number,
  'name' : string,
  'description' : string,
  'amenities' : Array<string>,
  'isActive' : boolean,
  'listingType' : ListingType,
  'location' : string,
  'photos' : Array<ExternalBlob>,
}
export type ListingType = { 'hotel' : null } |
  { 'homestay' : null };
export type TaxiRateType = { 'flat' : null } |
  { 'perKm' : null };
export interface TaxiRoute {
  'id' : string,
  'destination' : string,
  'origin' : string,
  'rate' : number,
  'isActive' : boolean,
  'estimatedKm' : [] | [number],
  'rateType' : TaxiRateType,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<[Listing], Listing>,
  'createTaxiRoute' : ActorMethod<[TaxiRoute], TaxiRoute>,
  'deleteBooking' : ActorMethod<[string], undefined>,
  'deleteListing' : ActorMethod<[string], undefined>,
  'deleteTaxiRoute' : ActorMethod<[string], undefined>,
  'getActiveListings' : ActorMethod<[], Array<Listing>>,
  'getActiveTaxiRoutes' : ActorMethod<[], Array<TaxiRoute>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListing' : ActorMethod<[string], Listing>,
  'getTaxiRoute' : ActorMethod<[string], TaxiRoute>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBooking' : ActorMethod<[Booking], Booking>,
  'updateBookingStatus' : ActorMethod<[string, BookingStatus], Booking>,
  'updateListing' : ActorMethod<[string, Listing], Listing>,
  'updateTaxiRoute' : ActorMethod<[string, TaxiRoute], TaxiRoute>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];