/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ListingType = IDL.Variant({
  'hotel' : IDL.Null,
  'homestay' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Listing = IDL.Record({
  'id' : IDL.Text,
  'pricePerNight' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Bool,
  'listingType' : ListingType,
  'location' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});
export const TaxiRateType = IDL.Variant({
  'flat' : IDL.Null,
  'perKm' : IDL.Null,
});
export const TaxiRoute = IDL.Record({
  'id' : IDL.Text,
  'destination' : IDL.Text,
  'origin' : IDL.Text,
  'rate' : IDL.Float64,
  'isActive' : IDL.Bool,
  'estimatedKm' : IDL.Opt(IDL.Float64),
  'rateType' : TaxiRateType,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const BookingType = IDL.Variant({
  'listing' : IDL.Null,
  'taxi' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'status' : BookingStatus,
  'checkIn' : IDL.Opt(IDL.Text),
  'listingId' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'guestName' : IDL.Text,
  'passengers' : IDL.Opt(IDL.Nat),
  'email' : IDL.Text,
  'pickupDate' : IDL.Opt(IDL.Text),
  'notes' : IDL.Text,
  'bookingType' : BookingType,
  'checkOut' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'totalPrice' : IDL.Float64,
  'taxiRouteId' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func([Listing], [Listing], []),
  'createTaxiRoute' : IDL.Func([TaxiRoute], [TaxiRoute], []),
  'deleteBooking' : IDL.Func([IDL.Text], [], []),
  'deleteListing' : IDL.Func([IDL.Text], [], []),
  'deleteTaxiRoute' : IDL.Func([IDL.Text], [], []),
  'getActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getActiveTaxiRoutes' : IDL.Func([], [IDL.Vec(TaxiRoute)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([IDL.Text], [Listing], ['query']),
  'getTaxiRoute' : IDL.Func([IDL.Text], [TaxiRoute], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBooking' : IDL.Func([Booking], [Booking], []),
  'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [Booking], []),
  'updateListing' : IDL.Func([IDL.Text, Listing], [Listing], []),
  'updateTaxiRoute' : IDL.Func([IDL.Text, TaxiRoute], [TaxiRoute], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ListingType = IDL.Variant({
    'hotel' : IDL.Null,
    'homestay' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Listing = IDL.Record({
    'id' : IDL.Text,
    'pricePerNight' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Bool,
    'listingType' : ListingType,
    'location' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const TaxiRateType = IDL.Variant({ 'flat' : IDL.Null, 'perKm' : IDL.Null });
  const TaxiRoute = IDL.Record({
    'id' : IDL.Text,
    'destination' : IDL.Text,
    'origin' : IDL.Text,
    'rate' : IDL.Float64,
    'isActive' : IDL.Bool,
    'estimatedKm' : IDL.Opt(IDL.Float64),
    'rateType' : TaxiRateType,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const BookingType = IDL.Variant({ 'listing' : IDL.Null, 'taxi' : IDL.Null });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'status' : BookingStatus,
    'checkIn' : IDL.Opt(IDL.Text),
    'listingId' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'guestName' : IDL.Text,
    'passengers' : IDL.Opt(IDL.Nat),
    'email' : IDL.Text,
    'pickupDate' : IDL.Opt(IDL.Text),
    'notes' : IDL.Text,
    'bookingType' : BookingType,
    'checkOut' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'totalPrice' : IDL.Float64,
    'taxiRouteId' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func([Listing], [Listing], []),
    'createTaxiRoute' : IDL.Func([TaxiRoute], [TaxiRoute], []),
    'deleteBooking' : IDL.Func([IDL.Text], [], []),
    'deleteListing' : IDL.Func([IDL.Text], [], []),
    'deleteTaxiRoute' : IDL.Func([IDL.Text], [], []),
    'getActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getActiveTaxiRoutes' : IDL.Func([], [IDL.Vec(TaxiRoute)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([IDL.Text], [Listing], ['query']),
    'getTaxiRoute' : IDL.Func([IDL.Text], [TaxiRoute], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBooking' : IDL.Func([Booking], [Booking], []),
    'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [Booking], []),
    'updateListing' : IDL.Func([IDL.Text, Listing], [Listing], []),
    'updateTaxiRoute' : IDL.Func([IDL.Text, TaxiRoute], [TaxiRoute], []),
  });
};

export const init = ({ IDL }) => { return []; };