/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TaxiRoute {
    id: string;
    destination: string;
    origin: string;
    rate: number;
    isActive: boolean;
    estimatedKm?: number;
    rateType: TaxiRateType;
}
export interface Listing {
    id: string;
    pricePerNight: number;
    name: string;
    description: string;
    amenities: Array<string>;
    isActive: boolean;
    listingType: ListingType;
    location: string;
    photos: Array<ExternalBlob>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Booking {
    id: string;
    status: BookingStatus;
    checkIn?: string;
    listingId?: string;
    createdAt: bigint;
    guestName: string;
    passengers?: bigint;
    email: string;
    pickupDate?: string;
    notes: string;
    bookingType: BookingType;
    checkOut?: string;
    phone: string;
    totalPrice: number;
    taxiRouteId?: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum BookingType {
    listing = "listing",
    taxi = "taxi"
}
export enum ListingType {
    hotel = "hotel",
    homestay = "homestay"
}
export enum TaxiRateType {
    flat = "flat",
    perKm = "perKm"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    claimFirstAdmin(): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createListing(listing: Listing): Promise<Listing>;
    createTaxiRoute(route: TaxiRoute): Promise<TaxiRoute>;
    deleteBooking(id: string): Promise<void>;
    deleteListing(id: string): Promise<void>;
    deleteTaxiRoute(id: string): Promise<void>;
    getActiveListings(): Promise<Array<Listing>>;
    getActiveTaxiRoutes(): Promise<Array<TaxiRoute>>;
    getAllBookings(): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getListing(id: string): Promise<Listing>;
    getTaxiRoute(id: string): Promise<TaxiRoute>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitBooking(booking: Booking): Promise<Booking>;
    updateBookingStatus(id: string, status: BookingStatus): Promise<Booking>;
    updateListing(id: string, listing: Listing): Promise<Listing>;
    updateTaxiRoute(id: string, route: TaxiRoute): Promise<TaxiRoute>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, BookingType as _BookingType, ExternalBlob as _ExternalBlob, Listing as _Listing, ListingType as _ListingType, TaxiRateType as _TaxiRateType, TaxiRoute as _TaxiRoute, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createListing(arg0: Listing): Promise<Listing> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(await to_candid_Listing_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Listing_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(await to_candid_Listing_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Listing_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTaxiRoute(arg0: TaxiRoute): Promise<TaxiRoute> {
        if (this.processError) {
            try {
                const result = await this.actor.createTaxiRoute(to_candid_TaxiRoute_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TaxiRoute_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTaxiRoute(to_candid_TaxiRoute_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TaxiRoute_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBooking(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async deleteListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async deleteTaxiRoute(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTaxiRoute(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTaxiRoute(arg0);
            return result;
        }
    }
    async getActiveListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveListings();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveListings();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveTaxiRoutes(): Promise<Array<TaxiRoute>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTaxiRoutes();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTaxiRoutes();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListing(arg0: string): Promise<Listing> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_Listing_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_Listing_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaxiRoute(arg0: string): Promise<TaxiRoute> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaxiRoute(arg0);
                return from_candid_TaxiRoute_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaxiRoute(arg0);
            return from_candid_TaxiRoute_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimFirstAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimFirstAdmin();
                return result;
            } catch(e) {
                return this.processError(e);
            }
        }
        const result = await this.actor.claimFirstAdmin();
        return result;
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitBooking(arg0: Booking): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(to_candid_Booking_n44(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Booking_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(to_candid_Booking_n44(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Booking_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBookingStatus(arg0: string, arg1: BookingStatus): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n46(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Booking_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n46(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Booking_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateListing(arg0: string, arg1: Listing): Promise<Listing> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, await to_candid_Listing_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Listing_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, await to_candid_Listing_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Listing_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTaxiRoute(arg0: string, arg1: TaxiRoute): Promise<TaxiRoute> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaxiRoute(arg0, to_candid_TaxiRoute_n22(this._uploadFile, this._downloadFile, arg1));
                return from_candid_TaxiRoute_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaxiRoute(arg0, to_candid_TaxiRoute_n22(this._uploadFile, this._downloadFile, arg1));
            return from_candid_TaxiRoute_n26(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_BookingType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingType): BookingType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ListingType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingType): ListingType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_Listing_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Promise<Listing> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TaxiRateType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaxiRateType): TaxiRateType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_TaxiRoute_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaxiRoute): TaxiRoute {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    pricePerNight: number;
    name: string;
    description: string;
    amenities: Array<string>;
    isActive: boolean;
    listingType: _ListingType;
    location: string;
    photos: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    pricePerNight: number;
    name: string;
    description: string;
    amenities: Array<string>;
    isActive: boolean;
    listingType: ListingType;
    location: string;
    photos: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        pricePerNight: value.pricePerNight,
        name: value.name,
        description: value.description,
        amenities: value.amenities,
        isActive: value.isActive,
        listingType: from_candid_ListingType_n18(_uploadFile, _downloadFile, value.listingType),
        location: value.location,
        photos: await from_candid_vec_n20(_uploadFile, _downloadFile, value.photos)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    destination: string;
    origin: string;
    rate: number;
    isActive: boolean;
    estimatedKm: [] | [number];
    rateType: _TaxiRateType;
}): {
    id: string;
    destination: string;
    origin: string;
    rate: number;
    isActive: boolean;
    estimatedKm?: number;
    rateType: TaxiRateType;
} {
    return {
        id: value.id,
        destination: value.destination,
        origin: value.origin,
        rate: value.rate,
        isActive: value.isActive,
        estimatedKm: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.estimatedKm)),
        rateType: from_candid_TaxiRateType_n29(_uploadFile, _downloadFile, value.rateType)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _BookingStatus;
    checkIn: [] | [string];
    listingId: [] | [string];
    createdAt: bigint;
    guestName: string;
    passengers: [] | [bigint];
    email: string;
    pickupDate: [] | [string];
    notes: string;
    bookingType: _BookingType;
    checkOut: [] | [string];
    phone: string;
    totalPrice: number;
    taxiRouteId: [] | [string];
}): {
    id: string;
    status: BookingStatus;
    checkIn?: string;
    listingId?: string;
    createdAt: bigint;
    guestName: string;
    passengers?: bigint;
    email: string;
    pickupDate?: string;
    notes: string;
    bookingType: BookingType;
    checkOut?: string;
    phone: string;
    totalPrice: number;
    taxiRouteId?: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n36(_uploadFile, _downloadFile, value.status),
        checkIn: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.checkIn)),
        listingId: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.listingId)),
        createdAt: value.createdAt,
        guestName: value.guestName,
        passengers: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.passengers)),
        email: value.email,
        pickupDate: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.pickupDate)),
        notes: value.notes,
        bookingType: from_candid_BookingType_n39(_uploadFile, _downloadFile, value.bookingType),
        checkOut: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.checkOut)),
        phone: value.phone,
        totalPrice: value.totalPrice,
        taxiRouteId: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.taxiRouteId))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hotel: null;
} | {
    homestay: null;
}): ListingType {
    return "hotel" in value ? ListingType.hotel : "homestay" in value ? ListingType.homestay : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flat: null;
} | {
    perKm: null;
}): TaxiRateType {
    return "flat" in value ? TaxiRateType.flat : "perKm" in value ? TaxiRateType.perKm : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    listing: null;
} | {
    taxi: null;
}): BookingType {
    return "listing" in value ? BookingType.listing : "taxi" in value ? BookingType.taxi : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Promise<Array<Listing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Listing_n16(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaxiRoute>): Array<TaxiRoute> {
    return value.map((x)=>from_candid_TaxiRoute_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n34(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_BookingType_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingType): _BookingType {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_Booking_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Booking): _Booking {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ListingType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingType): _ListingType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_Listing_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Listing): Promise<_Listing> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_TaxiRateType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaxiRateType): _TaxiRateType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_TaxiRoute_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaxiRoute): _TaxiRoute {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    pricePerNight: number;
    name: string;
    description: string;
    amenities: Array<string>;
    isActive: boolean;
    listingType: ListingType;
    location: string;
    photos: Array<ExternalBlob>;
}): Promise<{
    id: string;
    pricePerNight: number;
    name: string;
    description: string;
    amenities: Array<string>;
    isActive: boolean;
    listingType: _ListingType;
    location: string;
    photos: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        pricePerNight: value.pricePerNight,
        name: value.name,
        description: value.description,
        amenities: value.amenities,
        isActive: value.isActive,
        listingType: to_candid_ListingType_n12(_uploadFile, _downloadFile, value.listingType),
        location: value.location,
        photos: await to_candid_vec_n14(_uploadFile, _downloadFile, value.photos)
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    destination: string;
    origin: string;
    rate: number;
    isActive: boolean;
    estimatedKm?: number;
    rateType: TaxiRateType;
}): {
    id: string;
    destination: string;
    origin: string;
    rate: number;
    isActive: boolean;
    estimatedKm: [] | [number];
    rateType: _TaxiRateType;
} {
    return {
        id: value.id,
        destination: value.destination,
        origin: value.origin,
        rate: value.rate,
        isActive: value.isActive,
        estimatedKm: value.estimatedKm ? candid_some(value.estimatedKm) : candid_none(),
        rateType: to_candid_TaxiRateType_n24(_uploadFile, _downloadFile, value.rateType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: BookingStatus;
    checkIn?: string;
    listingId?: string;
    createdAt: bigint;
    guestName: string;
    passengers?: bigint;
    email: string;
    pickupDate?: string;
    notes: string;
    bookingType: BookingType;
    checkOut?: string;
    phone: string;
    totalPrice: number;
    taxiRouteId?: string;
}): {
    id: string;
    status: _BookingStatus;
    checkIn: [] | [string];
    listingId: [] | [string];
    createdAt: bigint;
    guestName: string;
    passengers: [] | [bigint];
    email: string;
    pickupDate: [] | [string];
    notes: string;
    bookingType: _BookingType;
    checkOut: [] | [string];
    phone: string;
    totalPrice: number;
    taxiRouteId: [] | [string];
} {
    return {
        id: value.id,
        status: to_candid_BookingStatus_n46(_uploadFile, _downloadFile, value.status),
        checkIn: value.checkIn ? candid_some(value.checkIn) : candid_none(),
        listingId: value.listingId ? candid_some(value.listingId) : candid_none(),
        createdAt: value.createdAt,
        guestName: value.guestName,
        passengers: value.passengers ? candid_some(value.passengers) : candid_none(),
        email: value.email,
        pickupDate: value.pickupDate ? candid_some(value.pickupDate) : candid_none(),
        notes: value.notes,
        bookingType: to_candid_BookingType_n48(_uploadFile, _downloadFile, value.bookingType),
        checkOut: value.checkOut ? candid_some(value.checkOut) : candid_none(),
        phone: value.phone,
        totalPrice: value.totalPrice,
        taxiRouteId: value.taxiRouteId ? candid_some(value.taxiRouteId) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingType): {
    hotel: null;
} | {
    homestay: null;
} {
    return value == ListingType.hotel ? {
        hotel: null
    } : value == ListingType.homestay ? {
        homestay: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaxiRateType): {
    flat: null;
} | {
    perKm: null;
} {
    return value == TaxiRateType.flat ? {
        flat: null
    } : value == TaxiRateType.perKm ? {
        perKm: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingType): {
    listing: null;
} | {
    taxi: null;
} {
    return value == BookingType.listing ? {
        listing: null
    } : value == BookingType.taxi ? {
        taxi: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
